### ISSUE TITLE
how to pass parameters to an existing python file?

### ISSUE THREAD

**Issue by tomerbsentinel** [Ambro17/slackify#11]
Hi,
I'm trying to deploy an app on Heroku.
The application contains 3 main files:

- The web file, taken from your project.
- My two main (separate) python files.

It seems I can't execute the other python file with some arguments ( I even tried to execute it w/o args. )
Heroku states that the file is not there. ( but, for sure it's there )
`FileNotFoundError: [Errno 2] No such file or directory: 'main_time.py': 'main_time.py'
`
If you look at the pic, I do have the file.
I tried to excecute it by calling this function:
subprocess.call(['main_time.py', '2391', username, password])

The whole code could be found [HERE](https://github.com/tobenary/timewatch_slack_filler) and I'm on this issue for 4 days already, (newbie).

So, I think that an example of "how to execute external python files" is also needed. ( Python with arguments )

Appreciate all the help I will get here.

**Comment by Ambro17** [comment]
Hello, how are you deploying your code into heroku? Do you have a git integration in which it redeploys on every git push?

My initial suspicion is that you have pushed your code into your github remote url, but not heroku's. You can read [this instructions](https://devcenter.heroku.com/articles/git#deploying-code) to sync heroku code with your local copy.

If that fails, you can try [installing heroku cli] and then run `heroku run bash`. That will enter to the directory present on your heroku deploy. From there you can inspect which files exist and which don't and get additional information for debuggin.

Let me know if it works for you or if you encounter any other problem

**Comment by tomerbsentinel** [comment]
Hi Ambro,
First, I'd like to thank you for your reply.

> Do you have a git integration in which it redeploys on every git push?
Yes, I have a git and every time I change it, it redeploys automatically in Heroku.

I know that the files are there for sure.
`C:\Users\tomerb>heroku run bash -a timewatch-slack-auto-filler
Running bash on ⬢ timewatch-slack-auto-filler... up, run.1196 (Free)
~ $ ll
bash: ll: command not found
~ $ ls
__init__.py  main_time.py  Procfile  requirements.txt  runtime.txt  slacki.py  timewatch.py
~ $`

Also, I created a print option inside the code, to validate it, and I got good results that the file is there as well.
![image](https://user-images.githubusercontent.com/38854357/89016897-24ebbf80-d322-11ea-8762-09aa0f96b1ea.png)

I will also try to subprocess.call on python (the Python interpreter) and then passing main_time.py in the argument list

**Comment by tomerbsentinel** [comment]
passing this to the main file worked.
`subprocess.call(['python', 'main_time.py', '2391', username, password])`

But, sometimes, if I insert wrong info, the dialogue box keeps staying on the screen.

**Comment by tomerbsentinel** [comment]
OK,
I read a lot, and figured out that I need to change the original file so, it will return his outputs.
I did it. ( See my git [HERE|https://github.com/tobenary/timewatch_slack_filler]
Now, I'm curious, why the script is running 3 times? ( see pic below ), plus, I can't send a msg to the end-user:
`@slackify.view("registration_form")
def register_callback(payload):
    """Handle registration form submission."""
username = payload['view']['state']['values']['username_block']['username_value']['value']
    password = payload['view']['state']['values']['password_block']['password_value']['value']
    tw_return = main_time.some_func('2391', username, password)
    print('**' + tw_return + '**')
    text = "*MANDATORY* - login to <checkin.timewatch.co.il/punch/punch2.php|timewatch> and check me."
    time.sleep(7)
    send_message(cli, channel=payload['user']['id'], blocks=text)
    send_message(cli, channel=payload['user']['id'], blocks=tw_return)
    # cli.chat_postMessage(channel=payload['user']['id'], text=text)
    # cli.chat_postMessage(channel=payload['user']['id'], text=tw_return)

    return ACK`


![image](https://user-images.githubusercontent.com/38854357/89029865-f8db3900-d337-11ea-9189-4e05d9cc0801.png)

**Comment by Ambro17** [comment]
I think the problem is the `time.sleep(7)`. Slack may retry the request if you fail to answer within the first 3 seconds.
Try removing that line and ensure that the send_message function is decorated with  `@async_func` to avoid blocking main thread.

Let me know if that works

**Comment by Ambro17** [comment]
On a side note, i don't recommend asking users to enter credentials on slack forms because they are unencrypted and they may leak into the logs and they are confidential info. 
Perhaps you are just doing some tests, but just in case..

**Comment by tomerbsentinel** [comment]
> Try removing that line.
I will try, thanks.
Question on the above:
So, after I send my credentials in the form (aka dialogue), how can I pass them to another function?
Isn't it that after I use the return ACK, I'm losing them? ( the payload data with all info )
My script (the other one that I'm calling, should work something like 10-15 sec.
I tried to sketch the full scenario clearly, so you'll understand my needs. ( sorry for my English, the sentence meant, that I appreciate your help  - not that you owe me something.)

> I don't recommend asking users to enter credentials.
This is an internal app, so, in this case, I don't care, but I totally agree with you, I can encode it and decode it back with a dedicated string.


![image](https://user-images.githubusercontent.com/38854357/89079647-9f065d80-d38f-11ea-92a1-3c355f4c1fee.png)

**Comment by Ambro17** [comment]
Hello, nice diagram, i now have a better understanding of your needs.

If i understood correctly this code should help you as a guide.
```
from flask import Flask
from slackify import Slackify, request, text_block, Slack, ACK
import json

from slackify.tasks import async_task


app = Flask(__name__)
slackify = Slackify(app=app)
cli = Slack('xoxb-SECRET-TOKEN')


@slackify.command
def fill_time():
    cli.views_open(
        trigger_id=request.form['trigger_id'],
        view=<view_dict>
    )
    return ACK


@slackify.view("registration_form")
def fill_time_callback():
    action = json.loads(request.form["payload"])
    response = action['view']['state']['values']

    # Login using user input in a background thread to avoid blocking this function
    login_to_timewatch(response)

    # Notify user that we are handling the command, also without blocking 
    send_message(cli, 'Your task was received and is being processed..', action['user']['id'])
    return ACK


@async_task
def login_to_timewatch(response):
    # Do yout login logic
    # ...
    # Then notify user of the outcome. This time the send message
    # doesn't need to be async as we are already in a background thread
    # So we use the cli call directly.
    cli.chat_postMessage(channel=user_id, user_id=user_id, text='Login successfull')


@async_task
def send_message(cli, text, user_id):
    return cli.chat_postMessage(channel=user_id, user_id=user_id, text=text)
```

The most important part is in `fill_time_callback` in which we must handle timewatch login and send_message in an @async_task function, so the execution on main thread continues and we can return ACK to slack server.
Meanwhile a background thread is sent for timewatch login (with the payload as an argument) and another one to notify the user that we received its command and we're working on it

I hope this helps

**Comment by tobenary** [comment]
It was indeed helpful!
And I think that I resolved the problem. (well, you actually resolved it).

One thing that was not working is the send command, so I used the CLI option instead and it worked.

**Comment by Ambro17** [comment]
Glad it was helpful 😄 
Do you think we can now close the issue?

**Comment by tomerbsentinel** [comment]
Sure, you can also add it as one of the examples. 
"executing_background_applications.py
