### ISSUE TITLE
[BUG] respond's slackify expects `str` but `dict`s are passed

### ISSUE THREAD

**Issue by gsilvapt** [Ambro17/slackify#13]
**Describe the bug**
When using the `respond` function from `slackify`'s slack file, it expects to receive a url and a message. Typing was set to `str` when the entire documentation recommends sending a dictionary with the blocks.

This raises some warnings in the editor and is just confusing. Could we clarify and update the typing type to `Dict` (from Python's official `Typing` library)?

**To Reproduce**
1. Use `respond()` method from `slackify.slack`.
2. Send params as per documented: `respond(payload['response_url'], {'blocks': [text_blok]})`

**Expected behavior**
If the library expects a str, a str should be use. If a dictionary, a dictionary should be used.

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Python: 3.8.5
 - Version 1.0.0

**Additional context**
As I think this is a minor bug, I'm opening a quick PR to fix this issue. Will mention this issue for reference.

**Comment by Ambro17** [comment]
Thank you for reporting the issue and also for the quick fix 🙂
