### ISSUE TITLE
Migrate to pyproject.toml

### ISSUE THREAD

**Issue by Ambro17** [Ambro17/slackify#24]
To get on the hype train, let's replace `setup.py` with `pyproject.toml`

**Comment by gsilvapt** [comment]
\if you want, I can start taking care of this when the Hacktoberfest starts 😄

**Comment by gsilvapt** [comment]
Please do :+1:

**Comment by gsilvapt** [comment]
Would you rather use this with setup tools or another build system?

**Comment by Ambro17** [comment]
setuptools would be enough as we don't need any special treatment to get a wheel

**Comment by Ambro17** [comment]
Merged
