### ISSUE TITLE
Does not appear possible to use as a Blueprint

### ISSUE THREAD

**Issue by twelvelabs** [Ambro17/slackify#3]
I have an existing flask app that includes a Blueprint (mounted at `/webhooks/slack`) for responding to slack commands. I'd love to replace that Blueprint with `slackify`, but it doesn't look like it's possible. Would you be open to changing `Flack` to be a Blueprint rather than a `Flask` subclass?

**Comment by Ambro17** [comment]
Yes! I would love to support separating commands into blueprints, it was the [#4 item in my roadmap.](https://github.com/Ambro17/slackify#roadmap)
I have some ideas in my mind how to achieve it, but first i wanted to finish de `@app.comment` funcionality.
If you want you can try to do a PR, you can find me as @BoedoCrow in telegram if you have any doubts about implementation

**Comment by Ambro17** [comment]
Just merged the `@app.comment` functionality. After testing the lib using the app factory pattern i will visit this enhancement proposal. I would really like for another one to contribute to this project so just tell me if you want to do it yourself and i'll give you the time and space.

**Comment by Ambro17** [comment]
I'm currently working on this and i'm close to finishing it. Just writing it down in case anyone was considering developing it
